model_a:
  anchor_symbol: "NVDA"
  correlation_window_days: 252
  candidate_pool_size: 250        # how many symbols you *consider* (pull later)
  active_universe_size: 40        # top-N correlated names you actually trade

model_b:
  atr_lookback_days: 14
  top_n_daily: 50
  min_avg_dollar_volume: 20000000 # liquidity floor (tune later)
  require_premarket: true         # premarket activity filter
  
tickers:
  Information Technology:
    - NVDA
    - AAPL
    - GOOG
    - MSFT
    - AMZN
    - TSM
    - META
    - AVGO
    - TSLA
    - 005930.KS
    - TECHY
    - ASML
    - ORCL
    - 000660.KS
    - NFLX
    - MU
    - PLTR
    - AMD
    - BABA
    - CSCO
    - AMAT
    - LRCX
    - IBM
    - SAP
    - KLAC
    - TXN
    - SHOP
    - APP
    - ANET
    - SU.PA
    - UBER
    - ADI
    - BKNG
    - QCOM
    - PDD
    - PANW
    - INTU
    - NOW
    - SONY
    - ARM
    - 8035.T
    - ADBE
    - 6857.T
    - SPOT
    - XIACF
    - CRWD
    - 2308.TW
    - DELL
    - 2317.TW
    - 6861.T
    - EQIX
    - ADP
    - MELI
    - 2454.TW
    - SNPS
    - CDNS
    - ABNB
    - STX
    - MRVL
    - DASH
    - SDNK
    - 0981.HK
    - NTES
    - 688256.SS
    - HOOD
    - NET
    - 7974.T
    - FTNT
    - SNOW
    - TEL
    - 36990.HK
    - IFX.DE
    - ADSK
    - SE
    - COIN
    - NXPI
    - 6146.T
    - MPWR

  Health Care:
    - UNH
    - HCA
    - MCK
    - CVS
    - CI
    - COR
    - ELV
    - SHL.DE
    - CAH
    - MDLN
    - FRE.DE
    - CNC
    - THC
    - Q0F.SI
    - 6618.HK
    - RDOR3.SA
    - OHI
    - 300015.SZ
    - FPH.NZ
    - FMS
    - ENSG
    - SOLV
    - GH
    - LLY
    - JNJ
    - ABBV
    - ROG.SW
    - NVS
    - AZN
    - MRK
    - AMGN
    - GILD
    - NVO
    - PFE
    - BMY
    - VRTX
    - GSK
    - SNY
    - REGN
    - TEK
    - ZTS
    - UCB.VI
    - 600276.SS
    - CSL.AX
    - GALD.SW
    - SUNPHARMA.NS
    - LONN.SW
    - ARGX
    - 2359.HK

  Financials:
    - JPM
    - V
    - MA
    - 1398.HK
    - BAC
    - 601939.SS
    - 601288.SS
    - HSBC
    - MS
    - WFC
    - 601988.SS
    - GS
    - RY
    - AXP
    - CBA.AX
    - MUFG
    - C
    - SCHW
    - SAN
    - TD
    - 3968.HK
    - HDB
    - SPGI
    - SMFG
    - D05.SI
    - UBS
    - BBVA
    - COF
    - SBIN.NS
    - CME
    - IBKR
    - BNP.PA
    - UCG.MI
    - 1120.SR
    - ISP.MI
    - IBN
    - NAB.AX
    - BMO
    - MFG
    - WBC.AX
    - ICE
    - CM
    - ITUB
    - BPAC3.SA
    - BNS
    - 601658.SS
    - 601328.SS
    - SBER.ME
    - MCO

  Consumer Discretionary:
    - WMT
    - COST
    - HD
    - BABA
    - ITX.MC
    - TJX
    - LOW
    - 9983.T
    - ROST
    - AZO
    - WES.AX
    - ATD.TO
    - WMMVF
    - TGT
    - L.TO
    - KR
    - AD.AS
    - JD
    - TSCO.L
    - DOL.TO
    - 8267.T
    - CPNG
    - DG
    - HM-B.ST
    - WOW.AX

  Industrials:
    - GE
    - CAT
    - CYATY
    - RTX
    - GEV
    - SMAWF
    - SIEGY
    - BA
    - SBGSF
    - SBGSY
    - EADSY
    - EADSF
    - DE
    - HON
    - ABLZF
    - LMT
    - SAFRY
    - ABBNY
    - SAFRF
    - UNP
    - SMEGF
    - SMERY
    - RYCEY
    - RYCEF
    - HTHIF
    - ETN
    - HTHIY
    - PH
    - MSBHF
    - MTSUY
    - NOC
    - MITSF
    - MITSY
    - DLEGF
    - HW
    - MHVYF
    - MHVIY
    - WM
    - GD
    - ATLPF
    - ITOCF
    - ATLFF
    - TT
    - ATLKY
    - VRT
    - BAESF
    - ITOCY